import { combineReducers, createStore } from "redux";
import { v4 } from "uuid";
let allData = [
  {
    name: "Shoes",
    price: 100,
    img: "/images/mens/men.jpg",
    id: v4(),
    qty: 1,
    category: "mens",
  },
  {
    name: "Shoes",
    price: 100,
    img: "/images/mens/men.jpg",
    id: v4(),
    qty: 1,
    category: "mens",
  },
  {
    name: "Shoes",
    price: 100,
    img: "/images/mens/men.jpg",
    id: v4(),
    qty: 1,
    category: "mens",
  },
  {
    name: "Shoes",
    price: 100,
    img: "/images/mens/men.jpg",
    id: v4(),
    qty: 1,
    category: "mens",
  },
  {
    name: "Shoes",
    price: 100,
    img: "/images/mens/men.jpg",
    id: v4(),
    qty: 1,
    category: "mens",
  },
  {
    name: "Shoes",
    price: 100,
    img: "/images/mens/men.jpg",
    id: v4(),
    qty: 1,
    category: "mens",
  },
  {
    name: "Shoes",
    price: 100,
    img: "/images/mens/men.jpg",
    id: v4(),
    qty: 1,
    category: "mens",
  },
  {
    name: "Shoes",
    price: 100,
    img: "/images/mens/men.jpg",
    id: v4(),
    qty: 1,
    category: "mens",
  },
  {
    name: "Shoes",
    price: 100,
    img: "/images/mens/men.jpg",
    id: v4(),
    qty: 1,
    category: "mens",
  },
  {
    name: "Shoes",
    price: 100,
    img: "/images/mens/men.jpg",
    id: v4(),
    qty: 1,
    category: "mens",
  },
  {
    name: "Shoes",
    price: 100,
    img: "/images/mens/men.jpg",
    id: v4(),
    qty: 1,
    category: "mens",
  },
  {
    name: "Shoes",
    price: 100,
    img: "/images/mens/men.jpg",
    id: v4(),
    qty: 1,
    category: "mens",
  },
  {
    name: "Shoes",
    price: 100,
    img: "/images/girl/girl.jpg",
    id: v4(),
    qty: 1,
    category: "girls",
  }, {
    name: "Shoes",
    price: 100,
    img: "/images/girl/girl.jpg",
    id: v4(),
    qty: 1,
    category: "girls",
  }, {
    name: "Shoes",
    price: 100,
    img: "/images/girl/girl.jpg",
    id: v4(),
    qty: 1,
    category: "girls",
  }, {
    name: "Shoes",
    price: 100,
    img: "/images/girl/girl.jpg",
    id: v4(),
    qty: 1,
    category: "girls",
  }, {
    name: "Shoes",
    price: 100,
    img: "/images/girl/girl.jpg",
    id: v4(),
    qty: 1,
    category: "girls",
  }, {
    name: "Shoes",
    price: 100,
    img: "/images/girl/girl.jpg",
    id: v4(),
    qty: 1,
    category: "girls",
  }, {
    name: "Shoes",
    price: 100,
    img: "/images/girl/girl.jpg",
    id: v4(),
    qty: 1,
    category: "girls",
  }, {
    name: "Shoes",
    price: 100,
    img: "/images/girl/girl.jpg",
    id: v4(),
    qty: 1,
    category: "girls",
  }, {
    name: "Shoes",
    price: 100,
    img: "/images/girl/girl.jpg",
    id: v4(),
    qty: 1,
    category: "girls",
  }, {
    name: "Shoes",
    price: 100,
    img: "/images/girl/girl.jpg",
    id: v4(),
    qty: 1,
    category: "girls",
  }, {
    name: "Shoes",
    price: 100,
    img: "/images/girl/girl.jpg",
    id: v4(),
    qty: 1,
    category: "girls",
  }, {
    name: "Shoes",
    price: 100,
    img: "/images/girl/girl.jpg",
    id: v4(),
    qty: 1,
    category: "girls",
  }, {
    name: "Shoes",
    price: 100,
    img: "/images/girl/girl.jpg",
    id: v4(),
    qty: 1,
    category: "girls",
  }, {
    name: "Shoes",
    price: 100,
    img: "/images/girl/girl.jpg",
    id: v4(),
    qty: 1,
    category: "girls",
  }, {
    name: "Shoes",
    price: 100,
    img: "/images/kids/kid.jpg",
    id: v4(),
    qty: 1,
    category: "kids",
  },{
    name: "Shoes",
    price: 100,
    img: "/images/kids/kid.jpg",
    id: v4(),
    qty: 1,
    category: "kids",
  },{
    name: "Shoes",
    price: 100,
    img: "/images/kids/kid.jpg",
    id: v4(),
    qty: 1,
    category: "kids",
  },{
    name: "Shoes",
    price: 100,
    img: "/images/kids/kid.jpg",
    id: v4(),
    qty: 1,
    category: "kids",
  },{
    name: "Shoes",
    price: 100,
    img: "/images/kids/kid.jpg",
    id: v4(),
    qty: 1,
    category: "kids",
  },{
    name: "Shoes",
    price: 100,
    img: "/images/kids/kid.jpg",
    id: v4(),
    qty: 1,
    category: "kids",
  },{
    name: "Shoes",
    price: 100,
    img: "/images/kids/kid.jpg",
    id: v4(),
    qty: 1,
    category: "kids",
  },{
    name: "Shoes",
    price: 100,
    img: "/images/kids/kid.jpg",
    id: v4(),
    qty: 1,
    category: "kids",
  },{
    name: "Shoes",
    price: 100,
    img: "/images/kids/kid.jpg",
    id: v4(),
    qty: 1,
    category: "kids",
  },{
    name: "Shoes",
    price: 100,
    img: "/images/kids/kid.jpg",
    id: v4(),
    qty: 1,
    category: "kids",
  },{
    name: "Shoes",
    price: 100,
    img: "/images/kids/kid.jpg",
    id: v4(),
    qty: 1,
    category: "kids",
  },{
    name: "Shoes",
    price: 100,
    img: "/images/kids/kid.jpg",
    id: v4(),
    qty: 1,
    category: "kids",
  },{
    name: " Special Shoes",
    price: 100,
    img: "/images/special/spe (2).jpg",
    id: v4(),
    qty: 1,
    category: "special",
  },{
    name: " Special Shoes",
    price: 100,
    img: "/images/special/spe (2).jpg",
    id: v4(),
    qty: 1,
    category: "special",
  },{
    name: " Special Shoes",
    price: 100,
    img: "/images/special/spe (3).jpg",
    id: v4(),
    qty: 1,
    category: "special",
  },{
    name: " Special Shoes",
    price: 100,
    img: "/images/special/spe (3).jpg",
    id: v4(),
    qty: 1,
    category: "special",
  },{
    name: " Special Shoes",
    price: 100,
    img: "/images/special/spe (1).jpg",
    id: v4(),
    qty: 1,
    category: "special",
  },{
    name: " Special Shoes",
    price: 100,
    img: "/images/special/spe (1).jpg",
    id: v4(),
    qty: 1,
    category: "special",
  },{
    img: "/images/Slider/slider (1).jpg",
    category: "slider",
  },{
    img: "/images/Slider/slider (2).jpg",
    category: "slider",
  },{
    img: "/images/Slider/slider (3).jpg",
    category: "slider",
  },{
    img: "/images/Slider/slider (4).jpg",
    category: "slider",
  },{
    img: "/images/Slider/slider (5).jpg",
    category: "slider",
  },
];

function cardData(oldData=allData, action){
    return oldData
}
let root = combineReducers({cardData,})
let store = createStore(root);
export default store;